apiVersion: v1
kind: Service
metadata:
  name: graphql-go-workshop
spec:
  type: LoadBalancer
  selector:
    app: graphql-go-workshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080